import test from "node:test";
import assert from "node:assert/strict";

import * as runtime from "../src/index.js";

test("runtime index exports expected surface", () => {
  assert.deepEqual(Object.keys(runtime).sort(), [
    "PROVIDER_IDS",
    "PROVIDER_OPERATION_NAMES",
    "buildClaudeInvocation",
    "buildCopilotInvocation",
    "buildGeminiInvocation",
    "buildKimiInvocation",
    "buildMiniMaxInvocation",
    "buildOpenCodeInvocation",
    "buildPiInvocation",
    "buildQwenEnv",
    "buildQwenInvocation",
    "extractClaudeText",
    "extractCopilotText",
    "extractGeminiText",
    "extractKimiText",
    "extractMiniMaxEventText",
    "extractMiniMaxLogPath",
    "extractMiniMaxResponseFromLogText",
    "extractOpenCodeText",
    "extractPiText",
    "extractQwenText",
    "getClaudeAuthStatus",
    "getClaudeAvailability",
    "getCopilotAuthStatus",
    "getCopilotAvailability",
    "getGeminiAuthStatus",
    "getGeminiAvailability",
    "getKimiAuthStatus",
    "getKimiAvailability",
    "getMiniMaxAuthStatus",
    "getMiniMaxAvailability",
    "getOpenCodeAuthStatus",
    "getOpenCodeAvailability",
    "getPiAuthStatus",
    "getPiAvailability",
    "getProviderRuntime",
    "getQwenAuthStatus",
    "getQwenAvailability",
    "listProviderRuntimes",
    "parseClaudeJsonResult",
    "parseClaudeStreamText",
    "parseCopilotStreamText",
    "parseGeminiStreamText",
    "parseKimiStreamText",
    "parseMiniMaxResponseBlocks",
    "parseOpenCodeJsonResult",
    "parseOpenCodeStreamText",
    "parsePiStreamText",
    "parseQwenStreamText",
    "runClaudePrompt",
    "runClaudePromptStreaming",
    "runCopilotPrompt",
    "runCopilotPromptStreaming",
    "runGeminiPrompt",
    "runGeminiPromptStreaming",
    "runKimiPrompt",
    "runKimiPromptStreaming",
    "runMiniMaxPrompt",
    "runMiniMaxPromptStreaming",
    "runOpenCodePrompt",
    "runOpenCodePromptStreaming",
    "runPiPrompt",
    "runPiPromptStreaming",
    "runProviderPrompt",
    "runProviderPromptStreaming",
    "runQwenPrompt",
    "runQwenPromptStreaming",
    "stripAnsiSgr",
  ]);
});
